# Generated by Django 3.1.7 on 2021-04-09 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0005_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.ManyToManyField(related_name='forum_comments', through='items.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
