# Generated by Django 3.1.7 on 2021-04-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='review',
        ),
    ]
