# Generated by Django 3.1.7 on 2021-04-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210409_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
