# Generated by Django 3.1.7 on 2021-04-09 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0010_auto_20210409_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.ManyToManyField(related_name='comments_owned', through='items.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
